# Generated by Django 5.0.1 on 2024-03-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('animal', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('informacion_adicional', models.CharField(blank=True, max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas')),
            ],
        ),
    ]
