# Generated by Django 5.0.1 on 2024-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
